services:
  backend:
    container_name: backend
    build: ./requirements/backend
    volumes:
      - ./requirements/backend/api/:/api
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine3.20
    ports:
      - "6379:6379"